In [2]:
import numpy as np

In [2]:
a=np.array([1,23])

In [3]:
print(a)

[ 1 23]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
n1=np.array([1,2,3])

In [6]:
n2=np.array([4,5,6])

In [7]:
print(n1+n2)
print(n1-n2)

[5 7 9]
[-3 -3 -3]


In [8]:
print(n1.sum())

6


# 2nd arrays

In [9]:
n1=np.array([[1,2],[3,4]])

In [10]:
print(n1)

[[1 2]
 [3 4]]


In [11]:
n1.ndim

2

In [12]:
print(np.size(n1))

4


In [13]:
n1=np.array([1,2,3,4,5,6,7])

In [14]:
print(n1[0])

1


In [16]:
n1=np.array([[1,2],[3,4]])

In [17]:
print(n1[0][1])

2


# slicing

In [18]:
 n=np.array([1,2,3,4,5,6])

In [19]:
print(n[1:3])

[2 3]


# COPY AND VIEW

In [3]:
n=np.array([1,2,3,4])

In [4]:
x=n.copy()

In [5]:
print(n)

[1 2 3 4]


In [6]:
print(x)

[1 2 3 4]


In [7]:
x[0]=10
print(x)

[10  2  3  4]


In [9]:
print(n)

[1 2 3 4]


In [10]:
n1=np.array([1,24,65,2])

In [14]:
v=n1.view()

In [15]:
print(n1)
print(v)

[ 1 24 65  2]
[ 1 24 65  2]


In [16]:
v[0]=11
print(v)

[11 24 65  2]


In [17]:
print(n1)

[11 24 65  2]


# shape

In [51]:
arr=np.array([[1,2,3],[6,7,9]])

In [52]:
print(arr.shape)

(2, 3)


In [53]:
print(arr)

[[1 2 3]
 [6 7 9]]


# reshape

In [58]:
arr=np.array([1,2,3,45,7,8,9,10,11])

In [59]:
print(arr.ndim)

1


In [60]:
arr1=arr.reshape(3,3)

In [61]:
print(arr1)

[[ 1  2  3]
 [45  7  8]
 [ 9 10 11]]


In [62]:
l=[1,2,34]

In [64]:
for i in l:
    print(i)

1
2
34


 # iterating

In [65]:
n=np.array([1,2,3,4,5,6,7])

In [66]:
for i in n:
    print(i)

1
2
3
4
5
6
7


# concat,stack

In [67]:
n1=np.array([1,2,3,4,5])

In [68]:
n2=np.array([6,7,8,9,10])

In [69]:
n3=np.concatenate((n1,n2))
print(n3)

[ 1  2  3  4  5  6  7  8  9 10]


In [70]:
n3=np.array([1,2,3])

In [71]:
n4=np.array([4,5,6])

In [73]:
n5=np.hstack((n3,n4))

In [74]:
print(n5)

[1 2 3 4 5 6]


In [75]:
n6=np.vstack((n3,n4))
print(n6)

[[1 2 3]
 [4 5 6]]


# split

In [76]:
a=np.array([1,2,3,4,5,6])

In [77]:
newa=np.array_split(a,3)

In [78]:
print(newa)

[array([1, 2]), array([3, 4]), array([5, 6])]
